---
restrictedRepos:
  include:
    - .github
    - SetRecoveryPassword
    - TagPrint
    - assetcache-exporter
    - autopkg
    - autopkg-gitops
    - epson-exporter
    - freshservice-label
    - leave-calendar
    - metabasis
    - onomazo
    - plinth
    - renovate-config
    - selectronic-exporter
    - slideforge
    - snipe-sync
    - talaria
    - woodbox
    - woodgate
    - woodstar
    - woodsweep
