---
repository:
  has_issues: true
  has_projects: false
  has_wiki: false
  has_discussions: false
  allow_merge_commit: false
  allow_squash_merge: true
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: BLANK
  allow_rebase_merge: false
  allow_auto_merge: true
  allow_update_branch: true
  delete_branch_on_merge: true

labels:
  exclude:
    - name: ^app/
    - name: ^area/
    - name: "autorelease: pending"
    - name: "autorelease: tagged"
    - name: release-please:force-run
    # stemma-catalog's software request workflow
    - name: ^software-request$
    - name: ^needs-input$

  include:
    - name: bug
      color: d73a4a
      description: Something isn't working
    - name: documentation
      color: 0075ca
      description: Improvements or additions to documentation
    - name: enhancement
      color: a2eeef
      description: New feature or request
    - name: question
      color: d876e3
      description: Further information is requested
    - name: wontfix
      color: ffffff
      description: This will not be worked on
    - name: do-not-merge
      color: ee0701
      description: Marks PR that is not (yet) in a mergeable state
    - name: stale
      color: c5def5
      description: Marked stale by automation due to inactivity

    - name: type/digest
      color: ffec19
      description: Issue relates to a digest version bump
    - name: type/patch
      color: ffec19
      description: Issue relates to a patch version bump
    - name: type/minor
      color: ff9800
      description: Issue relates to a minor version bump
    - name: type/major
      color: f6412d
      description: Issue relates to a major version bump
